general.import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
padding = { x = 10, y = 10 }

[font]
size = 15

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[cursor]
unfocused_hollow = false

[cursor.style]
shape = "Beam"
blinking = "Always"

[terminal]
osc52 = "CopyPaste"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "-", mods = "Control", action = "DecreaseFontSize"},
    { key = "=", mods = "Control", action = "IncreaseFontSize"},
    { key = "V", mods = "Control", action = "Paste" }
]
